### ISSUE TITLE
Raw Input register multiple joysticks help!

### ISSUE THREAD

**Issue by LeehamElectronics** [MysteriousJ/Joystick-Input-Examples#1]
Hi, I am trying to print axis information for multiple joysticks but I can not figure out how, I'm assuming I need to add to the folowing code somehow
```
// Register devices

	RAWINPUTDEVICE deviceList[2];
	deviceList[0].usUsagePage = HID_USAGE_PAGE_GENERIC;
	deviceList[0].usUsage = HID_USAGE_GENERIC_GAMEPAD;
	deviceList[0].dwFlags = RIDEV_INPUTSINK;
	deviceList[0].hwndTarget = hwnd;
	deviceList[1] = deviceList[0];
	deviceList[1].usUsage = HID_USAGE_GENERIC_JOYSTICK;
```

For example:
`deviceList[2].usUsage = HID_USAGE_GENERIC_JOYSTICK_NUMBER_TWO;`

Obv HID_USAGE_GENERIC_JOYSTICK_NUMBER_TWO is not an actual term. I'm really not sure where to go from here, any help would be greatly appreciated!

Thanks.

**Comment by MysteriousJ** [comment]
Registering for devices here will register for ALL devices that have the specified HID Usage. If your controllers are generic joysticks or gamepads, you will get raw input notifications from all that are connected.

**Comment by LeehamElectronics** [comment]
> Registering for devices here will register for ALL devices that have the specified HID Usage. If your controllers are generic joysticks or gamepads, you will get raw input notifications from all that are connected.

But how can I differentiate between different axis's? It just prints them all on the same value. 
Cheers

**Comment by MysteriousJ** [comment]
You can use the HID device's name to differentiate between controllers. The combined.cpp example stores deviceName in JoystickState so it can associate a RawInput event with a specific controller.
