### ISSUE TITLE
You forgot to call `winrt::init_apartment();` in WinRT example

### ISSUE THREAD

**Issue by DJm00n** [MysteriousJ/Joystick-Input-Examples#3]
See title :)

**Comment by MysteriousJ** [comment]
First I've heard of apartments. What is the functionality that's broken due to this missing call?

**Comment by DJm00n** [comment]
> First I've heard of apartments. What is the functionality that's broken due to this missing call?

This is needed to properly init WinRT. Is calls [RoInitialize](https://docs.microsoft.com/windows/win32/api/roapi/nf-roapi-roinitialize) under the hood.

I had random crashes in my own code without this call. Also there was crashes in SDL related to missing call to this function https://github.com/libsdl-org/SDL/issues/5270

See https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/get-started for details.
And https://github.com/contextfree/winrt-rust/issues/62#issuecomment-457286601 for info about apartments.

**Comment by MysteriousJ** [comment]
Added in https://github.com/MysteriousJ/Joystick-Input-Examples/commit/e2f196877de59134ac1499351d8e7391f4c6a3e0
