### ISSUE TITLE
CMake project

### ISSUE THREAD

**Issue by davidebeatrici** [MysteriousJ/Joystick-Input-Examples#4]
Would you like me to write a cross-platform CMake project?

**Comment by MysteriousJ** [comment]
Which platform is currently unsupported by the build.bat and makefile?

**Comment by davidebeatrici** [comment]
It would mostly be for consistency.

**Comment by MysteriousJ** [comment]
I would prefer to keep the build scripts low-level and platform-dependent since the same is true for all the source files. Hopefully, for example, the g++ commands in the makefile are so simple that a clang user would instantly know to build them with clang.

**Comment by davidebeatrici** [comment]
Makes sense.
