### ISSUE TITLE
"QWORD" data type not defined with 64 bit compiler

### ISSUE THREAD

**Issue by davidebeatrici** [MysteriousJ/Joystick-Input-Examples#5]
```cpp
src/rawinput_buffered.cpp(87): error C2065: 'QWORD': undeclared identifier
```

Workaround:

```cpp
using QWORD = UINT64;
```

Related:

https://github.com/MysteriousJ/Joystick-Input-Examples/blob/e2f196877de59134ac1499351d8e7391f4c6a3e0/src/rawinput_buffered.cpp#L1

**Comment by MysteriousJ** [comment]
Thanks, uncommented that line.
