### ISSUE TITLE
GDK's GameInput

### ISSUE THREAD

**Issue by mmozeiko** [MysteriousJ/Joystick-Input-Examples#6]
Here's one more way to get controller data on Windows (and Xbox) - through GDK GameInput:
https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/input/overviews/input-overview

From mrmixer on Handmade Network forum: https://handmade.network/forums/t/8710-using_microsoft_gameinput_api_with_multiple_controllers

**Comment by MysteriousJ** [comment]
I can't get data from this API on my machine. I tried mrmixer's exe as well: it prints
```
gamepad 1 input
got reading.
```
in a loop, but does not recognize A being pressed. I've tried with Xbox 360, Xbox One, and PS4 controllers.

**Comment by MysteriousJ** [comment]
Added overview and example for GDK GameInput. Would be nice to get displayName from it, but there seems to be a bug in the API that causes the field in DeviceInfo to always be null.
